Repository CS2103JAN2018-W09-B3/main, pull requests merged in 2018-04, with the labels that each got.

#89 Dashboard feature for v1.4
  src/main/java/seedu/address/commons/events/ui/ShowMilestonesEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowStudentDashboardEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowStudentNameInDashboardEvent.java
  src/main/java/seedu/address/logic/commands/AddMilestoneCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CheckTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMilestoneCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowDashboardCommand.java
  src/main/java/seedu/address/logic/commands/StudentBuilder.java
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddMilestoneCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CheckTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteMilestoneCommandParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowDashboardCommandParser.java
  src/main/java/seedu/address/logic/parser/UnfavouriteCommandParser.java
  src/main/java/seedu/address/model/student/dashboard/Dashboard.java
  src/main/java/seedu/address/model/student/dashboard/Date.java
  src/main/java/seedu/address/model/student/dashboard/Homework.java
  src/main/java/seedu/address/model/student/dashboard/Milestone.java
  src/main/java/seedu/address/model/student/dashboard/Progress.java
  src/main/java/seedu/address/model/student/dashboard/Task.java
  src/main/java/seedu/address/model/student/dashboard/UniqueHomeworkList.java
  src/main/java/seedu/address/model/student/dashboard/UniqueMilestoneList.java
  src/main/java/seedu/address/model/student/dashboard/UniqueTaskList.java
  src/main/java/seedu/address/model/student/dashboard/exceptions/DuplicateHomeworkException.java
  src/main/java/seedu/address/model/student/dashboard/exceptions/DuplicateMilestoneException.java
  src/main/java/seedu/address/model/student/dashboard/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/student/dashboard/exceptions/HomeworkNotFoundException.java
  src/main/java/seedu/address/model/student/dashboard/exceptions/MilestoneNotFoundException.java
  src/main/java/seedu/address/model/student/dashboard/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/storage/XmlAdaptedDashboard.java
  src/main/java/seedu/address/storage/XmlAdaptedMilestone.java
  src/main/java/seedu/address/storage/XmlAdaptedStudent.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/ui/DashboardPanel.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MilestoneCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MilestoneCard.fxml
  src/main/resources/view/TaskCard.fxml
  src/test/data/XmlSerializableAddressBookTest/typicalStudentAddressBook.xml
  src/test/data/XmlUtilTest/invalidStudentField.xml
  src/test/data/XmlUtilTest/missingStudentField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validStudent.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.enhancement

#83 Ability to identify some user commands from userInput
  src/main/java/seedu/address/logic/commands/ConversationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, type.enhancement, type.epic

#95 Contacts sync
  build.gradle
  src/main/java/seedu/address/external/GContactsManager.java
  src/main/java/seedu/address/external/exceptions/CredentialsException.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SyncCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement, type.epic

#124 Bug fixes for Code Review
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/model/lesson/Day.java
  src/main/java/seedu/address/model/programminglanguage/ProgrammingLanguage.java
Labels: priority.high

#139 Full implementation of Sync command
  .gitignore
  src/main/java/seedu/address/external/GCalendarService.java
  src/main/java/seedu/address/external/GContactsService.java
  src/main/java/seedu/address/external/GServiceManager.java
Labels: priority.high, type.enhancement, type.epic, type.story, type.task

#118 Improvement on Major Enhancement
  src/main/java/seedu/address/logic/commands/FindAndDeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindAndSelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindAndDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindAndSelectCommandParser.java
  src/main/resources/view/default.html
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.enhancement, type.epic
