Repository CS2103JAN2018-W09-B3/main, pull requests merged in 2018-03, with the labels that each got.

#52 Scheduler Fixes #37 #38 #39 #43 #44
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/StudentBuilder.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlySchedule.java
  src/main/java/seedu/address/model/Schedule.java
  src/main/java/seedu/address/model/lesson/Day.java
  src/main/java/seedu/address/model/lesson/Hour.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/LessonList.java
  src/main/java/seedu/address/model/lesson/Min.java
  src/main/java/seedu/address/model/lesson/Time.java
  src/main/java/seedu/address/model/lesson/exceptions/DuplicateLessonException.java
  src/main/java/seedu/address/model/lesson/exceptions/InvalidLessonTimeSlotException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.epic

#54 Updated User Guide Fixes #53
  docs/UserGuide.adoc
Labels: priority.high, type.task

#56 Developer guide update to include Schedule implementation
  docs/DeveloperGuide.adoc
Labels: priority.high, type.task

#74 Schedule Component implementations. Fixes #63
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/ScheduleChangedEvent.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Schedule.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/lesson/Day.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/LessonList.java
  src/main/java/seedu/address/model/lesson/exceptions/LessonNotFoundException.java
  src/main/java/seedu/address/model/student/Favourite.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueKey.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ScheduleStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedLesson.java
  src/main/java/seedu/address/storage/XmlAdaptedStudent.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlScheduleStorage.java
  src/main/java/seedu/address/storage/XmlSerializableSchedule.java
  src/test/data/XmlSerializableAddressBookTest/typicalStudentAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.high, type.enhancement, type.epic

#77 Implementing chatbot capablilities
  build.gradle
  docs/images/location_screenshot.png
  src/main/java/seedu/address/logic/commands/ConversationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: priority.high, status.ongoing, type.enhancement

#78 Formatted profile page template
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/model/StudentInfoChangedEvent.java
  src/main/java/seedu/address/commons/events/model/StudentInfoDisplayEvent.java
  src/main/java/seedu/address/commons/events/storage/RequiredStudentIndexChangeEvent.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RequiredStudentIndex.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlRequiredIndexStorage.java
  src/main/java/seedu/address/ui/BrowserPanel.java
Labels: priority.high, status.ongoing, type.enhancement

#80 Update UG for AddLesson and DeleteLesson command
  docs/UserGuide.adoc
Labels: priority.medium, type.task
